<a href="https://colab.research.google.com/github/Ananyadevaraju/CE888/blob/main/lab_4/movie_recommender.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import operator

In [ ]:
data = pd.ExcelFile('https://github.com/albanda/CE888/blob/master/lab4-recommender/movies_latent_factors.xlsx?raw=true')

In [ ]:
data.sheet_names

['Items', 'Users']

In [ ]:
df_items = pd.read_excel('https://github.com/albanda/CE888/blob/master/lab4-recommender/movies_latent_factors.xlsx?raw=true',sheet_name='Items',index_col=None)

In [ ]:
df_items.head()

Movie ID  ...  Factor15
0        11  ... -0.248806
1        12  ...  1.274993
2        13  ... -0.419092
3        14  ... -0.681191
4        22  ... -2.292566

[5 rows x 17 columns]

In [ ]:
df_users = pd.read_excel('https://github.com/albanda/CE888/blob/master/lab4-recommender/movies_latent_factors.xlsx?raw=true',sheet_name='Users', index_col=None)

In [ ]:
df_users.head()

User   Factor1   Factor2   Factor3  ...  Factor12  Factor13  Factor14  Factor15
0  4768 -0.204024  0.161079 -0.090447  ...  0.355404  0.007108 -0.118663 -0.039125
1   156 -0.189652 -0.178979 -0.091490  ... -0.048606  0.045916  0.113671  0.179873
2  5323 -0.115308 -0.090886 -0.053129  ... -0.019460  0.108372  0.054471 -0.109552
3   174 -0.227462 -0.272532 -0.017231  ... -0.082396  0.036767 -0.165438  0.050692
4  4529 -0.014616 -0.102218 -0.107935  ... -0.132836 -0.039897  0.129063  0.102669

[5 rows x 16 columns]

In [ ]:
df_users.shape, df_items.shape

((25, 16), (100, 17))

In [ ]:
# Which 3 movies would you recommend to User 174?
# user with ID 5338 will give to the movie with ID 155.
num_factors = df_users.shape[1]-1
user_pref = df_users[df_users['User'] == 3519].iloc[:, -num_factors:].values[0]
item_feat = df_items.iloc[:, -num_factors:].values

In [ ]:
preference = item_feat.dot(user_pref)

In [ ]:
preference


array([ 0.48534082, -0.08227086,  0.01983599,  0.13975328, -0.17719978,
        0.11271951,  0.08433738,  0.06682935,  0.09287665,  0.2584627 ,
       -0.04487359,  0.17840711,  0.03407909,  0.01665737,  0.04553261,
        0.02065168,  0.03979089,  0.12146753,  0.06185721,  0.08007232,
        0.11592771,  0.04094973, -0.06520509, -0.00649859, -0.08597423,
        0.19921222, -0.03646486,  0.19836899,  0.07157082,  0.07322261,
        0.06078828,  0.15943376,  0.21036455,  0.11335954,  0.08692182,
        0.01592376,  0.06332367, -0.12794075,  0.12013306, -0.02966947,
        0.0108208 ,  0.03525883, -0.0079035 , -0.01922981,  0.11866763,
        0.02726093, -0.09541437,  0.007967  ,  0.1562923 , -0.14828493,
        0.03421715, -0.33357331, -0.17800273,  0.14969457, -0.0584831 ,
        0.04138497, -0.08280496, -0.06034059, -0.07149923,  0.24594413,
        0.02798951, -0.11006304,  0.06742033, -0.18478517,  0.02433651,
       -0.22231437, -0.26076162, -0.04168923, -0.51177074,  0.06

In [ ]:
pd.DataFrame(preference).head(20)

0
0   0.485341
1  -0.082271
2   0.019836
3   0.139753
4  -0.177200
5   0.112720
6   0.084337
7   0.066829
8   0.092877
9   0.258463
10 -0.044874
11  0.178407
12  0.034079
13  0.016657
14  0.045533
15  0.020652
16  0.039791
17  0.121468
18  0.061857
19  0.080072

In [ ]:
top_values = pd.DataFrame(preference).nlargest(3, 0)
top_indices = top_values.index
list(top_indices)

[77, 0, 78]

In [ ]:
df_items.iloc[list(top_indices)]

Movie ID  ...  Factor15
77      1891  ... -0.115583
0         11  ... -0.248806
78      1892  ... -0.102475

[3 rows x 17 columns]

Quiz

In [ ]:
#Attempt 2

#Question 5

df_Fator = df_items[['Movie ID','Factor10']]

value = df_Fator[df_Fator['Movie ID']==98]['Factor10'].values[0]

round(value,3)


0.548

In [ ]:
#Question 6

df_factor2 = df_items[['Movie ID','Factor5']]
df_factor2.sort_values('Factor5')


Movie ID   Factor5
95      9806 -1.952736
34       280 -1.730847
52       607 -1.715186
70       862 -1.691165
11       105 -1.625467
..       ...       ...
79      1894  1.544977
47       597  1.729541
14       120  2.677432
16       122  2.688624
15       121  2.750878

[100 rows x 2 columns]

In [ ]:
#Question 7 and 8

num_factors = df_users.shape[1]-1
user_pref = df_users[df_users['User'] == 5338].iloc[:, -num_factors:].values[0]
item_feat = df_items.iloc[:, -num_factors:].values

In [ ]:
df_items[df_items['Movie ID']==597].index.values[0]

47

In [ ]:
#Question 9 
num_factors = df_users.shape[1]-1
user_pref = df_users[df_users['User'] == 4327].iloc[:, -num_factors:].values[0]
item_feat = df_items.iloc[:, -num_factors:].values

In [ ]:
preference = item_feat.dot(user_pref)

In [ ]:
preference

array([-5.71044742e-01,  7.01410201e-01,  9.57223781e-01,  3.12991853e-01,
       -3.62199616e-01, -1.38501942e-01,  3.40853715e-02, -1.76065210e-01,
        1.66234548e-01,  3.77310348e-01,  1.91713972e-01,  8.04537525e-01,
       -3.65379159e-01,  3.35828668e-01, -2.00020424e+00, -2.02421877e+00,
       -2.00524752e+00, -2.51763523e-01, -3.38759507e-01, -1.95467263e-01,
       -1.41032919e-01,  1.13379443e-01, -2.78711520e-01, -5.56532105e-02,
       -4.48453901e-01,  1.83515362e-01, -6.58166090e-02,  6.12487111e-01,
       -3.31922619e-01,  1.43369369e-02, -4.17054660e-02,  4.47399703e-01,
        8.90492306e-02,  5.89218353e-01,  8.35849315e-01,  1.06756752e+00,
       -2.60615270e-01, -5.55037299e-01,  4.74781078e-01,  2.98852362e-01,
       -7.25142638e-02, -6.09319124e-02,  6.85373309e-01,  5.78546289e-01,
        5.24647492e-02, -6.46812336e-02,  3.65719908e-01,  1.38604222e+00,
        8.48231867e-01,  4.40910187e-01,  4.06526293e-01, -3.42702729e-01,
        5.76931857e-01,  

In [ ]:
pd.DataFrame(preference).head(20)


0
0  -0.571045
1   0.701410
2   0.957224
3   0.312992
4  -0.362200
5  -0.138502
6   0.034085
7  -0.176065
8   0.166235
9   0.377310
10  0.191714
11  0.804538
12 -0.365379
13  0.335829
14 -2.000204
15 -2.024219
16 -2.005248
17 -0.251764
18 -0.338760
19 -0.195467

In [ ]:
top_values = pd.DataFrame(preference).nlargest(3, 0)
top_indices = top_values.index
list(top_indices)

[47, 35, 2]

In [ ]:
df_items.iloc[list(top_indices)]

Movie ID                 Title   Factor1  ...  Factor13  Factor14  Factor15
47       597        Titanic (1997)  1.567865  ...  0.370387  2.215933  0.456127
35       329  Jurassic Park (1993) -0.104238  ...  0.082476 -0.005909  1.466918
2         13   Forrest Gump (1994) -2.240888  ... -0.330276 -2.209004 -0.419092

[3 rows x 17 columns]

In [ ]:
#Question 10
num_factors = df_users.shape[1]-1
user_pref = df_users[df_users['User'] == 4327].iloc[:, -num_factors:].values[0]
item_feat = df_items.iloc[:, -num_factors:].values

In [ ]:
preference = item_feat.dot(user_pref)

In [ ]:
preference

array([-5.71044742e-01,  7.01410201e-01,  9.57223781e-01,  3.12991853e-01,
       -3.62199616e-01, -1.38501942e-01,  3.40853715e-02, -1.76065210e-01,
        1.66234548e-01,  3.77310348e-01,  1.91713972e-01,  8.04537525e-01,
       -3.65379159e-01,  3.35828668e-01, -2.00020424e+00, -2.02421877e+00,
       -2.00524752e+00, -2.51763523e-01, -3.38759507e-01, -1.95467263e-01,
       -1.41032919e-01,  1.13379443e-01, -2.78711520e-01, -5.56532105e-02,
       -4.48453901e-01,  1.83515362e-01, -6.58166090e-02,  6.12487111e-01,
       -3.31922619e-01,  1.43369369e-02, -4.17054660e-02,  4.47399703e-01,
        8.90492306e-02,  5.89218353e-01,  8.35849315e-01,  1.06756752e+00,
       -2.60615270e-01, -5.55037299e-01,  4.74781078e-01,  2.98852362e-01,
       -7.25142638e-02, -6.09319124e-02,  6.85373309e-01,  5.78546289e-01,
        5.24647492e-02, -6.46812336e-02,  3.65719908e-01,  1.38604222e+00,
        8.48231867e-01,  4.40910187e-01,  4.06526293e-01, -3.42702729e-01,
        5.76931857e-01,  

In [ ]:
pd.DataFrame(preference).head(20)


0
0  -0.571045
1   0.701410
2   0.957224
3   0.312992
4  -0.362200
5  -0.138502
6   0.034085
7  -0.176065
8   0.166235
9   0.377310
10  0.191714
11  0.804538
12 -0.365379
13  0.335829
14 -2.000204
15 -2.024219
16 -2.005248
17 -0.251764
18 -0.338760
19 -0.195467

In [ ]:
top_values = pd.DataFrame(preference).nlargest(2, 0)
top_indices = top_values.index
list(top_indices)

[47, 35]

In [ ]:
df_items.iloc[list(top_indices)]

Movie ID                 Title   Factor1  ...  Factor13  Factor14  Factor15
47       597        Titanic (1997)  1.567865  ...  0.370387  2.215933  0.456127
35       329  Jurassic Park (1993) -0.104238  ...  0.082476 -0.005909  1.466918

[2 rows x 17 columns]

In [ ]:
#Question 7

num_factors = df_users.shape[1]-1
user_pref = df_users[df_users['User'] == 4997].iloc[:, -num_factors:].values[0]
item_feat = df_items.iloc[:, -num_factors:].values

In [ ]:
df_items[df_items['Movie ID']==2164].index.values[0]


82

In [ ]:
preference = item_feat.dot(user_pref)

In [ ]:
round(preference[82],2)

-0.87

In [ ]:
#Question 8

num_factors = df_users.shape[1]-1
user_pref = df_users[df_users['User'] == 525].iloc[:, -num_factors:].values[0]
item_feat = df_items.iloc[:, -num_factors:].values

In [ ]:
df_items[df_items['Movie ID']==278].index.values[0]


33

In [ ]:
preference = item_feat.dot(user_pref)

In [ ]:
round(preference[33],2)

0.24