<a href="https://colab.research.google.com/github/Ananyadevaraju/CE888/blob/main/lab_4/my_recommender.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [22]:
#import libraries
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt

In [23]:
#load data
user_ratings_df = pd.read_csv('https://raw.githubusercontent.com/albanda/CE888/master/lab4-recommender/jester-data-1.csv', header = None)
print(user_ratings_df)

       0      1      2      3      4    ...    96     97     98     99     100
0       74  -7.82   8.79  -9.66  -8.16  ...  99.00  -5.63  99.00  99.00  99.00
1      100   4.08  -0.29   6.36   4.37  ...  -2.14   3.06   0.34  -4.32   1.07
2       49  99.00  99.00  99.00  99.00  ...  99.00  99.00  99.00  99.00  99.00
3       48  99.00   8.35  99.00  99.00  ...  99.00  99.00  99.00  99.00  99.00
4       91   8.50   4.61  -4.17  -5.39  ...   1.55   3.11   6.55   1.80   1.60
...    ...    ...    ...    ...    ...  ...    ...    ...    ...    ...    ...
24978  100   0.44   7.43   9.08   2.33  ...   9.03   6.55   8.69   8.79   7.43
24979   91   9.13  -8.16   8.59   9.08  ...  -8.20  -7.23  -8.59   9.13   8.45
24980   39  99.00  99.00  99.00  99.00  ...  99.00  99.00  99.00  99.00  99.00
24981   37  99.00  99.00  99.00  99.00  ...  99.00  99.00  99.00  99.00  99.00
24982   72   2.43   2.67  -3.98   4.27  ...  99.00  99.00  99.00  99.00  99.00

[24983 rows x 101 columns]


In [24]:
#dataset description
user_ratings_df.describe()

0             1    ...           99            100
count  24983.000000  24983.000000  ...  24983.000000  24983.000000
mean      72.467478     34.401435  ...     55.753357     60.138090
std       21.859600     46.707059  ...     49.237139     47.913531
min       36.000000     -9.950000  ...     -9.950000     -9.950000
25%       53.000000     -0.150000  ...      1.335000      3.930000
50%       72.000000      5.050000  ...     99.000000     99.000000
75%      100.000000     99.000000  ...     99.000000     99.000000
max      100.000000     99.000000  ...     99.000000     99.000000

[8 rows x 101 columns]

In [25]:
#checking for nan values
user_ratings_df.isna().sum()

0      0
1      0
2      0
3      0
4      0
      ..
96     0
97     0
98     0
99     0
100    0
Length: 101, dtype: int64

In [27]:
#replacing empty values with NaN which will be our test set
user_ratings_df = user_ratings_df.replace(99.00, np.NaN)

In [28]:
#drop column that does not contain ratings(number of jokes rated by each user)
user_ratings_df = user_ratings_df.drop(columns = [0])

In [29]:
user_ratings_df.head()

1     2     3     4     5     6    ...   95    96    97    98    99    100
0 -7.82  8.79 -9.66 -8.16 -7.52 -8.50  ...   NaN   NaN -5.63   NaN   NaN   NaN
1  4.08 -0.29  6.36  4.37 -2.38 -9.66  ... -0.19 -2.14  3.06  0.34 -4.32  1.07
2   NaN   NaN   NaN   NaN  9.03  9.27  ...   NaN   NaN   NaN   NaN   NaN   NaN
3   NaN  8.35   NaN   NaN  1.80  8.16  ...   NaN   NaN   NaN   NaN   NaN   NaN
4  8.50  4.61 -4.17 -5.39  1.36  1.60  ...  5.73  1.55  3.11  6.55  1.80  1.60

[5 rows x 100 columns]

In [30]:
#size of the dataset
user_ratings_df.shape

(24983, 100)

In [31]:
#using pandas to find the best and worst rated jokes
# for column in df:
#  mean(column) 
mean = user_ratings_df.mean(axis=0)
mean.max()

3.6650848950824937

In [32]:
arr = user_ratings_df.values
print(arr.shape)

(24983, 100)


In [33]:
rated = np.where(arr!=99)
print(len(rated[0]), rated[1].shape)

2498300 (2498300,)


In [34]:
def replace(orig, percentage=0.1):
  """
  Replaces 'percentage'% of the original values in 'orig' with 99's
  :param orig: original data array
  :param percentage: percentage of values to replace (0<percentage<1)
  """
  new_data = orig.copy()
  rated = np.where(~np.isnan(orig))
  n_rated = len(rated[0])
  idx = np.random.choice(n_rated, size=int(percentage*n_rated), replace=False)
  new_data[rated[0][idx], rated[1][idx]] = 99
  return new_data, (rated[0][idx], rated[1][idx])

In [35]:
new_arr, idx = replace(arr, 0.1)

In [36]:
arr[idx[0][0], idx[1][0]]

4.17

In [37]:
new_arr[idx[0][0], idx[1][0]]

99.0

In [38]:
n_latent_factors = 2

user_ratings = arr
# Initialise as random values
latent_user_preferences = np.random.random((user_ratings.shape[0], n_latent_factors))
latent_item_features = np.random.random((user_ratings.shape[1], n_latent_factors))

In [39]:
latent_item_features

array([[0.27412763, 0.85829511],
       [0.51621001, 0.46419741],
       [0.03639677, 0.11985172],
       [0.1154645 , 0.09886684],
       [0.6105901 , 0.59150143],
       [0.29645684, 0.59738518],
       [0.33356332, 0.03556331],
       [0.56482509, 0.59080539],
       [0.84985926, 0.33297975],
       [0.5334468 , 0.42873997],
       [0.01073198, 0.94544885],
       [0.17728248, 0.94917725],
       [0.23102232, 0.65586466],
       [0.1659368 , 0.42554355],
       [0.08684331, 0.42217957],
       [0.60939767, 0.29756898],
       [0.25911172, 0.83145024],
       [0.87801875, 0.03191267],
       [0.38055284, 0.66235258],
       [0.48689651, 0.67379352],
       [0.40750313, 0.22219219],
       [0.56838905, 0.26983058],
       [0.60845003, 0.5782933 ],
       [0.11425381, 0.57156115],
       [0.17073349, 0.08635444],
       [0.22886128, 0.62404681],
       [0.22742236, 0.16513968],
       [0.12057845, 0.21250962],
       [0.2866573 , 0.65157826],
       [0.53127856, 0.56016536],
       [0.

In [40]:
latent_user_preferences

array([[0.25528533, 0.18389194],
       [0.92262003, 0.02600343],
       [0.08564538, 0.10017153],
       ...,
       [0.09730908, 0.44806449],
       [0.8524272 , 0.36900512],
       [0.20774842, 0.16756003]])

In [41]:
def predict_rating(user_id, item_id):
    """ Predict a rating given a user_id and an item_id.
    """
    user_preference = latent_user_preferences[user_id]
    item_preference = latent_item_features[item_id]
    return user_preference.dot(item_preference)


def train(user_id, item_id, rating, alpha=0.0001):
    #print(item_id)
    predicted_rating = predict_rating(user_id, item_id)
    err =  predicted_rating - rating
    #print(err)
    user_pref_values = latent_user_preferences[user_id]
    latent_user_preferences[user_id] -= alpha * err * latent_item_features[item_id]
    latent_item_features[item_id] -= alpha * err * user_pref_values
    return err
    

def sgd(iterations):
    """ Iterate over all users and all items and train for 
        a certain number of iterations
    """
    mse_history = []
    for iteration in range(iterations):
        error = []
        for user_id in range(latent_user_preferences.shape[0]):
            for item_id in range(latent_item_features.shape[0]):
                rating = user_ratings[user_id, item_id]
                if not np.isnan(rating) and rating!=99:
                    err = train(user_id, item_id, rating)
                    error.append(err)
        mse = (np.array(error) ** 2).mean()   
        if (iteration % 10000) == 0:
            print('Iteration %d/%d:\tMSE=%.6f' % (iteration, iterations, mse))
            mse_history.append(mse)
    return mse_history

In [ ]:
num_iter = 100
hist = sgd(num_iter)  # Note how the MSE decreases with the number of iterations
plt.figure()
plt.plot(np.arange(0, num_iter, 10), hist)
plt.xlabel("Iterations")
plt.ylabel("MSE")
plt.show()

Iteration 0/100:	MSE=23.068537


In [20]:
predictions = latent_user_preferences.dot(latent_item_features.T)
predictions

array([[1.66223146, 1.058395  , 1.06946213, ..., 2.00774887, 0.90714723,
        2.68751342],
       [1.31146277, 0.86856797, 0.85893464, ..., 1.53351858, 0.65223995,
        1.98371633],
       [1.80615576, 1.18334778, 1.1771214 , ..., 2.13135203, 0.92260557,
        2.78438421],
       ...,
       [0.26947241, 0.16633775, 0.17100502, ..., 0.33339417, 0.15699298,
        0.45706735],
       [1.46489747, 0.95819527, 0.9540048 , ..., 1.73101631, 0.75125764,
        2.26469391],
       [1.39096251, 0.8429371 , 0.8756116 , ..., 1.74453833, 0.84003321,
        2.42316347]])

In [21]:
values = [zip(arr[i], predictions[i]) for i in range(predictions.shape[0])]
comparison_data = pd.DataFrame(values)
comparison_data.columns = user_ratings_df.columns

AttributeError: ignored

In [ ]:
comparison_data

Movie dataset notebook: 